# Generated by Django 4.2.2 on 2025-08-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите превью (картинка)",
                null=True,
                upload_to="materials/preview",
                verbose_name="Картинка",
            ),
        ),
    ]
